### PR TITLE
Support for Resque 2.0.0

### PR DESCRIPTION
**Pull request by jiikko**

### CODE REVIEW

**Review by RobertoSchneiders — APPROVED** [review]

**Comment by RobertoSchneiders** [comment]
just what I was looking for, thanks @jiikko. 

I'll appreciate if you can merge and generate a new revision @iloveitaly.

**Comment by iloveitaly** [comment]
@RobertoSchneiders @jiikko before merging we need to ensure that there has been no change in the implementation of `unregister_signal_handlers` between resque versions.

Can one of you confirm that there has been no code change to that method?

**Comment by RobertoSchneiders** [comment]
@iloveitaly I can confirm that there has been no code change in that method. Last change was made 2 years ago :)

https://github.com/resque/resque/blame/v2.0.0/lib/resque/worker.rb#L406

**Comment by iloveitaly** [comment]
Perfect! Merging this in now.

**Pull request merged**
